export const dataGames = [
    {
        id: 1,
        nameGame: "God of War Ragnarök",
        developer: "Santa Monica Studio",
        rating: 9.5,
        genre: ["Action", "Adventure"],
        platform: ["PS5", "PS4"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 2,
        nameGame: "Starfield",
        developer: "Bethesda Game Studios",
        rating: 8.8,
        genre: ["RPG", "Adventure"],
        platform: ["PC", "Xbox Series"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 3,
        nameGame: "Civilization VII",
        developer: "Firaxis Games",
        rating: 9.0,
        genre: ["Strategy"],
        platform: ["PC", "PS5", "Xbox Series", "Nintendo Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 4,
        nameGame: "Dead Space Remake",
        developer: "Motive Studio",
        rating: 8.7,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS5", "Xbox Series"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 5,
        nameGame: "Forza Horizon 5",
        developer: "Playground Games",
        rating: 9.2,
        genre: ["Racing", "Adventure"],
        platform: ["PC", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 6,
        nameGame: "Horizon Forbidden West",
        developer: "Guerrilla Games",
        rating: 9.0,
        genre: ["Action", "Adventure"],
        platform: ["PS5", "PS4"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 7,
        nameGame: "Elden Ring",
        developer: "FromSoftware",
        rating: 9.6,
        genre: ["RPG", "Action"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 8,
        nameGame: "Tetris Effect: Connected",
        developer: "Monstars Inc.",
        rating: 8.5,
        genre: ["Puzzle"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One", "Nintendo Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 39.99,
    },
    {
        id: 9,
        nameGame: "Resident Evil 4 Remake",
        developer: "Capcom",
        rating: 9.3,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS5", "PS4", "Xbox Series"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 10,
        nameGame: "Gran Turismo 7",
        developer: "Polyphony Digital",
        rating: 8.9,
        genre: ["Racing", "Simulation"],
        platform: ["PS5", "PS4"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 11,
        nameGame: "Spider-Man: Miles Morales",
        developer: "Insomniac Games",
        rating: 8.8,
        genre: ["Action", "Adventure"],
        platform: ["PS5", "PS4"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 49.99,
    },
    {
        id: 12,
        nameGame: "Avowed",
        developer: "Obsidian Entertainment",
        rating: 8.5,
        genre: ["RPG", "Adventure"],
        platform: ["PC", "Xbox Series"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 13,
        nameGame: "Stardew Valley",
        developer: "ConcernedApe",
        rating: 9.0,
        genre: ["Simulation", "RPG"],
        platform: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 14.99,
    },
    {
        id: 14,
        nameGame: "Amnesia: Rebirth",
        developer: "Frictional Games",
        rating: 8.0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 29.99,
    },
    {
        id: 15,
        nameGame: "F1 24",
        developer: "Codemasters",
        rating: 8.4,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 16,
        nameGame: "Astro Bot",
        developer: "Team Asobi",
        rating: 9.4,
        genre: ["Platformer", "Adventure"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 17,
        nameGame: "Diablo IV",
        developer: "Blizzard Entertainment",
        rating: 8.7,
        genre: ["RPG", "Action"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 18,
        nameGame: "Portal 2",
        developer: "Valve",
        rating: 9.5,
        genre: ["Puzzle", "Platformer"],
        platform: ["PC", "PS4", "Xbox One"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 19.99,
    },
    {
        id: 19,
        nameGame: "Silent Hill 2 Remake",
        developer: "Bloober Team",
        rating: 8.9,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 20,
        nameGame: "Assetto Corsa Competizione",
        developer: "Kunos Simulazioni",
        rating: 8.6,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 39.99,
    },
    {
        id: 21,
        nameGame: "The Last of Us Part II Remastered",
        developer: "Naughty Dog",
        rating: 9.3,
        genre: ["Action", "Adventure"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 49.99,
    },
    {
        id: 22,
        nameGame: "The Outer Worlds 2",
        developer: "Obsidian Entertainment",
        rating: 8.8,
        genre: ["RPG", "Adventure"],
        platform: ["PC", "Xbox Series"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 23,
        nameGame: "Fire Emblem: Three Houses",
        developer: "Intelligent Systems",
        rating: 9.0,
        genre: ["Strategy", "RPG"],
        platform: ["Nintendo Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 24,
        nameGame: "Outlast Trials",
        developer: "Red Barrels",
        rating: 8.2,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {
        id: 25,
        nameGame: "Microsoft Flight Simulator",
        developer: "Asobo Studio",
        rating: 9.1,
        genre: ["Simulation"],
        platform: ["PC", "Xbox Series"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 26,
        nameGame: "Ratchet & Clank: Rift Apart",
        developer: "Insomniac Games",
        rating: 9.0,
        genre: ["Action", "Platformer"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 27,
        nameGame: "Baldur’s Gate 3",
        developer: "Larian Studios",
        rating: 9.7,
        genre: ["RPG", "Strategy"],
        platform: ["PC", "PS5", "Xbox Series"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 28,
        nameGame: "Among Us",
        developer: "Innersloth",
        rating: 8.5,
        genre: ["Party"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One", "Nintendo Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 4.99,
    },
    {
        id: 29,
        nameGame: "Phasmophobia",
        developer: "Kinetic Games",
        rating: 8.4,
        genre: ["Horror", "Survival"],
        platform: ["PC"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 13.99,
    },
    {
        id: 30,
        nameGame: "Dirt 5",
        developer: "Codemasters",
        rating: 8.0,
        genre: ["Racing"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 31,
        nameGame: "Demon’s Souls",
        developer: "Bluepoint Games",
        rating: 9.2,
        genre: ["Action", "RPG"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 32,
        nameGame: "Halo Infinite",
        developer: "343 Industries",
        rating: 8.6,
        genre: ["Shooter", "Action"],
        platform: ["PC", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 33,
        nameGame: "Animal Crossing: New Horizons",
        developer: "Nintendo",
        rating: 9.0,
        genre: ["Simulation"],
        platform: ["Nintendo Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 34,
        nameGame: "Layers of Fear (2023)",
        developer: "Bloober Team",
        rating: 8.1,
        genre: ["Horror"],
        platform: ["PC", "PS5", "Xbox Series"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 29.99,
    },
    {
        id: 35,
        nameGame: "Forza Motorsport",
        developer: "Turn 10 Studios",
        rating: 8.8,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox Series"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 36,
        nameGame: "Final Fantasy XVI",
        developer: "Square Enix",
        rating: 8.9,
        genre: ["Action", "RPG"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 37,
        nameGame: "Cyberpunk 2077: Phantom Liberty",
        developer: "CD Projekt Red",
        rating: 9.0,
        genre: ["RPG", "Action"],
        platform: ["PC", "PS5", "Xbox Series"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 29.99,
    },
    {
        id: 38,
        nameGame: "Pikmin 4",
        developer: "Nintendo",
        rating: 8.7,
        genre: ["Strategy"],
        platform: ["Nintendo Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 39,
        nameGame: "Fears to Fathom",
        developer: "Rayll",
        rating: 7.8,
        genre: ["Horror"],
        platform: ["PC"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 14.99,
    },
    {
        id: 40,
        nameGame: "iRacing",
        developer: "iRacing.com Motorsport Simulations",
        rating: 8.5,
        genre: ["Racing", "Simulation"],
        platform: ["PC"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 13.99,
    },
    {
        id: 41,
        nameGame: "Marvel’s Spider-Man 2",
        developer: "Insomniac Games",
        rating: 9.3,
        genre: ["Action", "Adventure"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 42,
        nameGame: "Gears 5",
        developer: "The Coalition",
        rating: 8.5,
        genre: ["Shooter", "Action"],
        platform: ["PC", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 39.99,
    },
    {
        id: 43,
        nameGame: "Splatoon 3",
        developer: "Nintendo",
        rating: 8.6,
        genre: ["Shooter"],
        platform: ["Nintendo Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 44,
        nameGame: "Dead by Daylight",
        developer: "Behaviour Interactive",
        rating: 8.2,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One", "Nintendo Switch"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 19.99,
    },
    {
        id: 45,
        nameGame: "NASCAR Heat 5",
        developer: "704Games",
        rating: 7.9,
        genre: ["Racing"],
        platform: ["PC", "PS4", "Xbox One"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 29.99,
    },
    {
        id: 46,
        nameGame: "Returnal",
        developer: "Housemarque",
        rating: 8.8,
        genre: ["Action", "Shooter"],
        platform: ["PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 69.99,
    },
    {
        id: 47,
        nameGame: "Sea of Thieves",
        developer: "Rare",
        rating: 8.4,
        genre: ["Adventure", "Sandbox"],
        platform: ["PC", "PS5", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 39.99,
    },
    {
        id: 48,
        nameGame: "Super Smash Bros. Ultimate",
        developer: "Bandai Namco",
        rating: 9.3,
        genre: ["Fighting"],
        platform: ["Nintendo Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 59.99,
    },
    {
        id: 49,
        nameGame: "Soma",
        developer: "Frictional Games",
        rating: 8.5,
        genre: ["Horror", "Adventure"],
        platform: ["PC", "PS4", "Xbox One"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 29.99,
    },
    {
        id: 50,
        nameGame: "Wreckfest",
        developer: "Bugbear Entertainment",
        rating: 8.0,
        genre: ["Racing", "Action"],
        platform: ["PC", "PS5", "PS4", "Xbox Series", "Xbox One"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 39.99,
    }
];