export const dataGames = [
     {   id: 1,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 2,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 3,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 29.99,
    },
{   id: 4,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 5,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 54.99,
    },
    {   id: 6,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 7,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 8,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 29.99,
    },
    {   id: 9,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 10,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 54.99,
    },

    {   id: 11,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 12,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 13,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 29.99,
    },
{   id: 14,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 15,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 54.99,
    },
    {   id: 16,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 17,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 18,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 29.99,
    },
    {   id: 19,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 20,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 54.99,
    },

    {   id: 21,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 22,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 23,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 29.99,
    },
{   id: 24,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 25,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 54.99,
    },
    {   id: 26,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 27,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 28,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 29.99,
    },
    {   id: 29,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 30,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 54.99,
    },

    {   id: 31,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 32,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 33,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 29.99,
    },
{   id: 34,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 35,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 54.99,
    },
    {   id: 36,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 37,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 38,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 29.99,
    },
    {   id: 39,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 40,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 54.99,
    },

    {   id: 41,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image1.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 42,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image2.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 43,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image3.jpg",
        available: true,
        price: 29.99,
    },
{   id: 44,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image4.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 45,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image5.jpg",
        available: true,
        price: 54.99,
    },
    {   id: 46,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Action", "Adventure"],
        platform: ["PC", "PS5"],
        imageUrl: "https://example.com/image6.jpg",
        available: true,
        price: 59.99,
    },
    {   id: 47,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["RPG", "Fantasy"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image7.jpg",
        available: true,
        price: 49.99,
    },
    {   id: 48,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Puzzle", "Strategy"],
        platform: ["PC", "Switch"],
        imageUrl: "https://example.com/image8.jpg",
        available: true,
        price: 29.99,
    },
    {   id: 49,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Horror", "Survival"],
        platform: ["PC", "PS4"],
        imageUrl: "https://example.com/image9.jpg",
        available: true,
        price: 39.99,
    },
    {   id: 50,
        nameGame:"",
        developer:"",
        rating: 0,
        genre: ["Racing", "Simulation"],
        platform: ["PC", "Xbox"],
        imageUrl: "https://example.com/image10.jpg",
        available: true,
        price: 54.99,
    }
]